// SPDX-FileCopyrightText: Copyright 2026 NVIDIA CORPORATION & AFFILIATES
// SPDX-License-Identifier: Apache-2.0

//! Generator for `conformance/protobuf-conformance/` fixtures.
//!
//! ## Last-one-wins for scalar / singular submessage fields
//!
//! The [Protocol Buffers encoding spec](https://protobuf.dev/programming-guides/encoding/#optional)
//! defines the runtime rule for repeated occurrences of singular
//! fields:
//! The quoted and adapted documentation is third-party material licensed
//! under the three-clause BSD license, not material relicensed under the
//! Apache-2.0 declaration on this NVIDIA-authored generator. See the
//! repository `THIRD_PARTY_NOTICES.md` for the pinned source revision,
//! copyright notice, license, and disclaimer.
//!
//! > Normally, an encoded message would never have more than one
//! > instance of a non-repeated field. However, parsers are expected
//! > to handle the case in which they do. For numeric types and
//! > strings, if the same field appears multiple times, the parser
//! > accepts the last value it sees.
//!
//! > For embedded message fields, the parser merges multiple instances
//! > of the same field, as if with the
//! > `Message::MergeFrom` method...
//!
//! ## Unknown field handling
//!
//! The Protocol Buffers proto3 language guide defines unknown fields:
//!
//! > Unknown fields are well-formed protocol buffer serialized data
//! > representing fields that the parser does not recognize. For example,
//! > when an old binary parses data sent by a new binary with new fields,
//! > those new fields become unknown fields in the old binary.
//!
//! > Proto3 messages preserve unknown fields and include them during
//! > parsing and in the serialized output, which matches proto2 behavior.
//!
//! `transcription-api.md` (the repo-level spec) interprets that
//! latitude with `OuterConformance` levels (`STRICT`, `PERMISSIVE`,
//! `SIGNATURE_STRICT`). The fixtures below pin the on-wire bytes that
//! drive each level's decision.
//!
//! ## Malformed wire encodings
//!
//! The malformed fixtures exercise field number zero, the first field
//! number above the protobuf range, the two invalid wire types, truncated and
//! overflowing tag and length varints, and a declared length that exceeds the
//! remaining input. These byte sequences are original negative fixtures
//! generated by this repository.

use crate::util::write_bytes;
use crate::wire::{lendel, tag, varint, varint_field, yss};
use yamlsigil_pinned_dir::PinnedDir;

pub fn generate(dir: &PinnedDir) -> std::io::Result<()> {
    let sig64 = [0u8; 64];
    let payload: &[u8] = b"hello: world\n";
    let inner = yss(1, None, &sig64);

    // 1. Sanity baseline
    let mut f1 = lendel(1, payload);
    f1.extend(lendel(2, &inner));
    write_bytes(dir, "valid-baseline.binpb", &f1)?;

    // 2. Duplicate outer payload
    let mut f2 = lendel(1, payload);
    f2.extend(lendel(1, b"second: payload\n"));
    f2.extend(lendel(2, &inner));
    write_bytes(dir, "duplicate-outer-payload.binpb", &f2)?;

    // 3. Duplicate outer signature submessage
    let inner_alt = yss(1, None, &[0xff; 64]);
    let mut f3 = lendel(1, payload);
    f3.extend(lendel(2, &inner));
    f3.extend(lendel(2, &inner_alt));
    write_bytes(dir, "duplicate-outer-signature.binpb", &f3)?;

    // 4. Unknown outer field at number 5 (varint)
    let mut unknown = tag(5, 0);
    unknown.extend(varint(42));
    let mut f4 = lendel(1, payload);
    f4.extend(lendel(2, &inner));
    f4.extend(unknown);
    write_bytes(dir, "unknown-outer-field.binpb", &f4)?;

    // 5. Inner duplicate alg varint
    let mut bad_inner = varint_field(1, 1);
    bad_inner.extend(varint_field(1, 2));
    bad_inner.extend(lendel(3, &sig64));
    let mut f5 = lendel(1, payload);
    f5.extend(lendel(2, &bad_inner));
    write_bytes(dir, "inner-strict-duplicate-alg.binpb", &f5)?;

    // 6. Present-empty outer signature submessage
    let mut f6 = lendel(1, payload);
    f6.extend(lendel(2, b""));
    write_bytes(dir, "present-empty-outer-signature.binpb", &f6)?;

    // 7. Binary payload not representable in YAML envelope. The
    //    payload is a single octet `0x72` (the RFC 8032 §7.1 Test 2
    //    message-byte choice, reused here as a compact non-YAML-
    //    envelope-fit example: one byte, no trailing line terminator).
    //    A protobuf-form verifier MUST accept this artifact (no YAML
    //    envelope rules apply); protobuf -> YAML transcoding MUST
    //    fail at the YAML Compose step with `InvalidPayloadBytes`.
    let binary_payload: &[u8] = b"\x72";
    let inner_binary = yss(1, None, &sig64);
    let mut f7 = lendel(1, binary_payload);
    f7.extend(lendel(2, &inner_binary));
    write_bytes(dir, "binary-payload-no-yaml-fit.binpb", &f7)?;

    // 8. Field number zero is never valid. Append it after a complete
    //    baseline so a decoder must validate through EOF rather than
    //    returning after extracting the known fields.
    let mut f8 = f1.clone();
    f8.extend([0x02, 0x01, b'x']);
    write_bytes(dir, "invalid-field-zero.binpb", &f8)?;

    // 9. Protobuf field numbers are limited to 29 bits. The first value
    //    outside that range is appended as a length-delimited tag.
    let mut f9 = f1.clone();
    f9.extend(tag(1_u64 << 29, 2));
    f9.extend([0x01, b'x']);
    write_bytes(dir, "out-of-range-field-number.binpb", &f9)?;

    // 10. A ten-octet tag varint whose final payload bit would exceed
    //     u64 must reject rather than wrap or alias a valid field.
    let mut f10 = f1.clone();
    f10.push(0x8a);
    f10.extend([0x80; 8]);
    f10.extend([0x02, 0x01, b'p']);
    write_bytes(dir, "overflowing-tag-varint.binpb", &f10)?;

    // 11. A tag varint ends while its continuation bit is still set.
    let mut f11 = f1.clone();
    f11.push(0x80);
    write_bytes(dir, "truncated-tag-varint.binpb", &f11)?;

    // 12. A length varint ends while its continuation bit is still set.
    let mut f12 = f1.clone();
    f12.extend(tag(5, 2));
    f12.push(0x80);
    write_bytes(dir, "truncated-length-varint.binpb", &f12)?;

    // 13. A ten-octet length varint whose final payload bit would exceed
    //     u64 must reject rather than wrap to a shorter declared length.
    let mut f13 = f1.clone();
    f13.extend(tag(5, 2));
    f13.extend([0x80; 9]);
    f13.push(0x02);
    write_bytes(dir, "overflowing-length-varint.binpb", &f13)?;

    // 14. A length-delimited unknown field declares 2^32 + 5 octets
    //     but supplies one. Its declared length exceeds the remaining
    //     input.
    let mut f14 = f1.clone();
    f14.extend(tag(5, 2));
    f14.extend(varint((1_u64 << 32) + 5));
    f14.push(b'p');
    write_bytes(dir, "oversized-length.binpb", &f14)?;

    // 15–16. Wire types 6 and 7 are not protobuf wire types.
    for wire_type in [6, 7] {
        let mut fixture = f1.clone();
        fixture.extend(tag(5, wire_type));
        write_bytes(
            dir,
            &format!("invalid-wire-type-{wire_type}.binpb"),
            &fixture,
        )?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The baseline fixture's outer payload field starts with the
    /// known tag/length prefix for `field=1, wire=LEN, len=13`.
    #[test]
    fn baseline_starts_with_expected_tag_and_length() {
        let payload: &[u8] = b"hello: world\n";
        let prefix = lendel(1, payload);
        // 0x0A = (1 << 3) | 2
        // 0x0D = 13 (varint)
        assert_eq!(prefix[0], 0x0A);
        assert_eq!(prefix[1], 0x0D);
        assert_eq!(&prefix[2..], payload);
    }

    #[test]
    fn first_out_of_range_field_number_uses_more_than_32_tag_bits() {
        let encoded = tag(1_u64 << 29, 2);
        assert_eq!(encoded, vec![0x82, 0x80, 0x80, 0x80, 0x10]);
    }

    #[test]
    fn oversized_length_is_encoded_without_host_usize_conversion() {
        assert_eq!(
            varint((1_u64 << 32) + 5),
            vec![0x85, 0x80, 0x80, 0x80, 0x10]
        );
    }

    #[test]
    fn truncated_varint_retains_its_continuation_bit() {
        assert_ne!(0x80 & 0x80, 0);
    }

    #[test]
    fn overflowing_length_varint_exceeds_uint64() {
        let mut encoded = vec![0x80; 9];
        encoded.push(0x02);
        assert_eq!(encoded.len(), 10);
        assert_eq!(encoded[9] & 0x7f, 0x02);
    }

    #[test]
    fn invalid_wire_type_tags_are_single_octets() {
        assert_eq!(tag(5, 6), vec![0x2e]);
        assert_eq!(tag(5, 7), vec![0x2f]);
    }
}
